name: worklin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.5
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.9
  geolocator: ^12.0.0
  get_storage: ^2.1.1
  pinput: ^3.0.1
  syncfusion_flutter_charts: ^25.2.5
  jiffy: ^6.2.1
  flutter_native_splash: ^2.3.13
  qr_code_scanner: ^1.0.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  equatable: ^2.0.5
  delightful_toast: ^1.1.0
  latlong2: ^0.9.1
  sn_progress_dialog: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.3.13
  flutter_test:
    sdk: flutter

  lint: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/app_icons/
    - assets/app_icons/svg/
    - assets/app_images/
    - assets/translations/
    - .env
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Space_Grotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-SemiBold.ttf
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-VariableFont_wght.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/static/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ThinItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-VariableFont_wght.ttf

